feat: ctrl+c trap

diff --git a/jukebox b/jukebox
--- a/jukebox
+++ b/jukebox
@@ -1,4 +1,5 @@
 #!/bin/bash
+# License: GPLv3.0
 # polarhive.net/jukebox
 set -e
 export priority=false
@@ -18,17 +19,15 @@ usage() {
     echo "  -a: <artist name>"
     echo "  -g: <genre name>"
     echo "  -s: <song name>"
-    echo ""
     echo "  -u: <lastfm: username>"
     echo "  -m: <lastfm: mix | recommended | library>"
-    echo ""
     echo "  -l: vosk: search songs with your voice"
     echo "  -y: use ytmusic tags for songs"
     echo "  -c: top charts in your region (setup your api_key)"
     exit 1
 }
 
-# santizie input
+# sanitize input
 clean() {
     q=$(echo $q | tr ' ' '+')
 }
@@ -77,17 +76,24 @@ loop() {
 
 # download song
 dl() {
-    if [ "$ytm_backend" = true ]; then
-        yt-dlp ${ytargs} --playlist-end 1 --default-search "https://music.youtube.com/search?q=" "$q" --parse-metadata "title:%(title)s" --parse-metadata "artist:%(artist)s" --add-metadata -o '%(artist)s - %(title)s.%(ext)s' && queue || echo "ERROR: https://youtu.be/${id}"
+    if [ "$ytm_backend" = true ]; then 
+        if yt-dlp ${ytargs} --playlist-end 1 --default-search "https://music.youtube.com/search?q=" "$q" --parse-metadata "title:%(title)s" --parse-metadata "artist:%(artist)s" --add-metadata -o '%(artist)s - %(title)s.%(ext)s'; then 
+            queue
+        else
+            echo "ERROR: https://youtu.be/${id}"
+        fi
     else
-        yt-dlp ${ytargs} --postprocessor-args "ffmpeg:-metadata title=${t@Q} -metadata artist=${a@Q}" -o "$a - $t.%(ext)s" "$id" && queue || echo "ERROR: https://youtu.be/${id}"
+        if yt-dlp ${ytargs} --postprocessor-args "ffmpeg:-metadata title=${t@Q} -metadata artist=${a@Q}" -o "$a - $t.%(ext)s" "$id"; then
+            queue
+        else
+            echo "ERROR: https://youtu.be/${id}"
+        fi
     fi
 }
 
 # queue song
 queue() {
-    rm ~/$music_folder/.tmp/dl/*.part -f && mpc -q update
-    sleep 0.1
+    rm ~/$music_folder/.tmp/dl/*.part -f; sleep 0.1; mpc -q update
     name=$(ls -u | head -1)
     if [ "$priority" = true ]; then
         if [ "$(mpc playlist | wc -l)" -eq 0 ]; then
@@ -151,3 +157,6 @@ done
 if [ $OPTIND -eq 1 ]; then
     play_user
 fi
+
+# ctrl+c trap
+trap exit 1 SIGINT
