feat/psync: sanity check before syncing

diff --git a/psync b/psync
--- a/psync
+++ b/psync
@@ -1,7 +1,19 @@
 #!/bin/bash
-cd ~/.local/share/.Music/; rm -rf ~/.cache/songs; mkdir ~/.cache/songs
-rm ~/.local/share/mpd/playlists/songs.m3u; mpc -q save songs
+# skip if empty
+set -e
+if [ "$(mpc playlist | wc -l)" -eq 0 ]; then
+    notify-send "Add songs"
+    exit 1
+fi
+
+# cleanup
+cd ~/.local/share/.Music/
+rm -rf ~/.cache/songs; mkdir ~/.cache/songs
+rm ~/.local/share/mpd/playlists/songs.m3u; mpc -q save songs; mpc -q clear
+adb shell mkdir -p /sdcard/Music
+
+# copy to phone
 rsync -avL --files-from="$HOME/.local/share/mpd/playlists/songs.m3u" ./ ~/.cache/songs
 adb push ~/.cache/songs/* "/sdcard/Music"
-adb push ~/.local/share/mpd/playlists/songs.m3u "/sdcard/Music";
-mpc -q clear
+adb push ~/.local/share/mpd/playlists/songs.m3u "/sdcard/Music"
+
